# Generated by Django 6.0.1 on 2026-02-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_lunch_dinner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["student", "month", "year"],
                name="billing_bil_student_f95c01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["status"], name="billing_bil_status_ddee07_idx"),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["month", "year"], name="billing_bil_month_7755bf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(
                fields=["student", "status"], name="billing_bil_student_f34722_idx"
            ),
        ),
    ]
