# Generated by Django 6.0.1 on 2026-02-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("online", "Online"),
                    ("upi", "UPI"),
                    ("cheque", "Cheque"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
