# Generated by Django 6.0.1 on 2026-02-18 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_add_indexes"),
        ("payments", "0002_alter_payment_payment_method"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "status"], name="payments_pa_student_2663d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["bill", "status"], name="payments_pa_bill_id_ffa04d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "payment_method"],
                name="payments_pa_status_5e9688_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_date"], name="payments_pa_payment_1d6e55_idx"
            ),
        ),
    ]
